"""empty message

Revision ID: 1f326b63fbdd
Revises: 2d57e166d00f
Create Date: 2020-04-15 14:47:20.445006

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1f326b63fbdd'
down_revision = '2d57e166d00f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auth_user', 'created_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=False)
    op.alter_column('auth_user', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=False)
    op.alter_column('orga_address', 'created_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=False)
    op.alter_column('orga_address', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=False)
    op.alter_column('orga_company', 'created_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=False)
    op.alter_column('orga_company', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=False)
    op.alter_column('orga_finesset', 'created_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=False)
    op.alter_column('orga_finesset', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=False)
    op.alter_column('orga_organization', 'created_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=False)
    op.alter_column('orga_organization', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=False)
    op.alter_column('orga_platform', 'created_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=False)
    op.alter_column('orga_platform', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orga_platform', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=True)
    op.alter_column('orga_platform', 'created_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=True)
    op.alter_column('orga_organization', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=True)
    op.alter_column('orga_organization', 'created_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=True)
    op.alter_column('orga_finesset', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=True)
    op.alter_column('orga_finesset', 'created_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=True)
    op.alter_column('orga_company', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=True)
    op.alter_column('orga_company', 'created_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=True)
    op.alter_column('orga_address', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=True)
    op.alter_column('orga_address', 'created_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=True)
    op.alter_column('auth_user', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=True)
    op.alter_column('auth_user', 'created_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=True)
    # ### end Alembic commands ###
