"""empty message

Revision ID: 2d57e166d00f
Revises: 2cefdce77c3d
Create Date: 2020-04-15 13:27:02.317561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d57e166d00f'
down_revision = '2cefdce77c3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orga_address',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('street', sa.String(length=50), nullable=True),
    sa.Column('zipcode', sa.String(length=10), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('lon', sa.Integer(), nullable=True),
    sa.Column('lat', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orga_company',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('siret', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orga_finesset',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finess_et', sa.String(length=15), nullable=False),
    sa.Column('finess_ej', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orga_platform',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orga_organization',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('object_type', sa.Unicode(length=255), nullable=True),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['orga_address.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('auth_user', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('auth_user', sa.Column('object_id', sa.Integer(), nullable=True))
    op.add_column('auth_user', sa.Column('object_type', sa.Unicode(length=255), nullable=True))
    op.add_column('auth_user', sa.Column('phone_number', sa.String(length=10), nullable=True))
    op.add_column('auth_user', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_user', 'updated_at')
    op.drop_column('auth_user', 'phone_number')
    op.drop_column('auth_user', 'object_type')
    op.drop_column('auth_user', 'object_id')
    op.drop_column('auth_user', 'created_at')
    op.drop_table('orga_organization')
    op.drop_table('orga_platform')
    op.drop_table('orga_finesset')
    op.drop_table('orga_company')
    op.drop_table('orga_address')
    # ### end Alembic commands ###
